---
name: Z-Wave JS to MQTT
version: dev
slug: zwavejs2mqtt
description: Fully configurable Z-Wave JS to MQTT gateway and control panel; based on Zwavejs2Mqtt
url: https://github.com/hassio-addons/addon-zwavejs2mqtt
ingress: true
ingress_stream: true
panel_title: Z-Wave JS
panel_icon: mdi:z-wave
startup: system
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
discovery:
  - zwave_js
services:
  - mqtt:want
watchdog: http://[HOST]:[PORT:8099]/health/zwave
uart: true
udev: true
map:
  - share:rw
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
ports:
  3000/tcp: null
ports_description:
  3000/tcp: Z-Wave JS communication
