---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  packages: read
  pull-requests: read
  security-events: write

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/app-ci.yaml@3846ae0fd09acec8ac1ac308ceacd052b9d01bec # v2.0.6
    with:
      slug: "zwave-js-ui"
