---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/release-drafter.yaml@3846ae0fd09acec8ac1ac308ceacd052b9d01bec # v2.0.6
